/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1beta1 "github.com/imtiaz246/custom-controller/pkg/apis/cho.me/v1beta1"
	chomev1beta1 "github.com/imtiaz246/custom-controller/pkg/client/applyconfiguration/cho.me/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFooServers implements FooServerInterface
type FakeFooServers struct {
	Fake *FakeChoV1beta1
	ns   string
}

var fooserversResource = v1beta1.SchemeGroupVersion.WithResource("fooservers")

var fooserversKind = v1beta1.SchemeGroupVersion.WithKind("FooServer")

// Get takes name of the fooServer, and returns the corresponding fooServer object, and an error if there is any.
func (c *FakeFooServers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FooServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fooserversResource, c.ns, name), &v1beta1.FooServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooServer), err
}

// List takes label and field selectors, and returns the list of FooServers that match those selectors.
func (c *FakeFooServers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FooServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fooserversResource, fooserversKind, c.ns, opts), &v1beta1.FooServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.FooServerList{ListMeta: obj.(*v1beta1.FooServerList).ListMeta}
	for _, item := range obj.(*v1beta1.FooServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fooServers.
func (c *FakeFooServers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fooserversResource, c.ns, opts))

}

// Create takes the representation of a fooServer and creates it.  Returns the server's representation of the fooServer, and an error, if there is any.
func (c *FakeFooServers) Create(ctx context.Context, fooServer *v1beta1.FooServer, opts v1.CreateOptions) (result *v1beta1.FooServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fooserversResource, c.ns, fooServer), &v1beta1.FooServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooServer), err
}

// Update takes the representation of a fooServer and updates it. Returns the server's representation of the fooServer, and an error, if there is any.
func (c *FakeFooServers) Update(ctx context.Context, fooServer *v1beta1.FooServer, opts v1.UpdateOptions) (result *v1beta1.FooServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fooserversResource, c.ns, fooServer), &v1beta1.FooServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooServer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFooServers) UpdateStatus(ctx context.Context, fooServer *v1beta1.FooServer, opts v1.UpdateOptions) (*v1beta1.FooServer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(fooserversResource, "status", c.ns, fooServer), &v1beta1.FooServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooServer), err
}

// Delete takes name of the fooServer and deletes it. Returns an error if one occurs.
func (c *FakeFooServers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(fooserversResource, c.ns, name, opts), &v1beta1.FooServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFooServers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fooserversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.FooServerList{})
	return err
}

// Patch applies the patch and returns the patched fooServer.
func (c *FakeFooServers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FooServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fooserversResource, c.ns, name, pt, data, subresources...), &v1beta1.FooServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooServer), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied fooServer.
func (c *FakeFooServers) Apply(ctx context.Context, fooServer *chomev1beta1.FooServerApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.FooServer, err error) {
	if fooServer == nil {
		return nil, fmt.Errorf("fooServer provided to Apply must not be nil")
	}
	data, err := json.Marshal(fooServer)
	if err != nil {
		return nil, err
	}
	name := fooServer.Name
	if name == nil {
		return nil, fmt.Errorf("fooServer.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fooserversResource, c.ns, *name, types.ApplyPatchType, data), &v1beta1.FooServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooServer), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeFooServers) ApplyStatus(ctx context.Context, fooServer *chomev1beta1.FooServerApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.FooServer, err error) {
	if fooServer == nil {
		return nil, fmt.Errorf("fooServer provided to Apply must not be nil")
	}
	data, err := json.Marshal(fooServer)
	if err != nil {
		return nil, err
	}
	name := fooServer.Name
	if name == nil {
		return nil, fmt.Errorf("fooServer.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fooserversResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1beta1.FooServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooServer), err
}
