apiVersion: cho.me/v1beta1
kind: FooServer
metadata:
  labels:
    app.kubernetes.io/created-by: fooserver
  name: fooservers.resource1
  namespace: default
spec:
  deploymentSpec:
    name: "foo-server-deployment"
    podReplicas: 1
    podContainerPort: 3000
  serviceSpec:
    name: "foo-server-service"
    targetPort: 3000
    port: 3000
    type: NodePort
    nodePort: 30100
  secretSpec:
    name: "foo-server-secret"
    username: "admin"
    password: "password"
