/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// FooServerDeploymentSpecApplyConfiguration represents an declarative configuration of the FooServerDeploymentSpec type for use
// with apply.
type FooServerDeploymentSpecApplyConfiguration struct {
	DeploymentName   *string `json:"deploymentName,omitempty"`
	PodReplicas      *int32  `json:"podReplicas,omitempty"`
	PodContainerPort *int32  `json:"podContainerPort,omitempty"`
}

// FooServerDeploymentSpecApplyConfiguration constructs an declarative configuration of the FooServerDeploymentSpec type for use with
// apply.
func FooServerDeploymentSpec() *FooServerDeploymentSpecApplyConfiguration {
	return &FooServerDeploymentSpecApplyConfiguration{}
}

// WithDeploymentName sets the DeploymentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentName field is set to the value of the last call.
func (b *FooServerDeploymentSpecApplyConfiguration) WithDeploymentName(value string) *FooServerDeploymentSpecApplyConfiguration {
	b.DeploymentName = &value
	return b
}

// WithPodReplicas sets the PodReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodReplicas field is set to the value of the last call.
func (b *FooServerDeploymentSpecApplyConfiguration) WithPodReplicas(value int32) *FooServerDeploymentSpecApplyConfiguration {
	b.PodReplicas = &value
	return b
}

// WithPodContainerPort sets the PodContainerPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodContainerPort field is set to the value of the last call.
func (b *FooServerDeploymentSpecApplyConfiguration) WithPodContainerPort(value int32) *FooServerDeploymentSpecApplyConfiguration {
	b.PodContainerPort = &value
	return b
}
