/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// FooServerSecretSpecApplyConfiguration represents an declarative configuration of the FooServerSecretSpec type for use
// with apply.
type FooServerSecretSpecApplyConfiguration struct {
	SecretName   *string `json:"secretName,omitempty"`
	UsernameData *string `json:"usernameData,omitempty"`
	PasswordData *string `json:"passwordData,omitempty"`
}

// FooServerSecretSpecApplyConfiguration constructs an declarative configuration of the FooServerSecretSpec type for use with
// apply.
func FooServerSecretSpec() *FooServerSecretSpecApplyConfiguration {
	return &FooServerSecretSpecApplyConfiguration{}
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *FooServerSecretSpecApplyConfiguration) WithSecretName(value string) *FooServerSecretSpecApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithUsernameData sets the UsernameData field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsernameData field is set to the value of the last call.
func (b *FooServerSecretSpecApplyConfiguration) WithUsernameData(value string) *FooServerSecretSpecApplyConfiguration {
	b.UsernameData = &value
	return b
}

// WithPasswordData sets the PasswordData field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PasswordData field is set to the value of the last call.
func (b *FooServerSecretSpecApplyConfiguration) WithPasswordData(value string) *FooServerSecretSpecApplyConfiguration {
	b.PasswordData = &value
	return b
}
